### ISSUE TITLE
User profiles management

### ISSUE THREAD

**Issue by gingervik** [SOURC3XYZ/Sourc3-Web-Client#20]
connected with https://github.com/SOURC3XYZ/sourc3/issues/65

<img width="1131" alt="Screenshot 2022-05-10 at 13 49 57" src="https://user-images.githubusercontent.com/28015224/167632273-90154cdf-9162-4b11-8088-dd0c1f1d3a1a.png">

Designs: https://www.figma.com/file/3UUMChv0qaOOkHoddpEFgA/SOURC3?node-id=16%3A93

**Comment by KatsiarynaV** [comment]
Checked
