### ISSUE TITLE
redisign Send Page

### ISSUE THREAD

**Issue by JenkJS** [SOURC3XYZ/Sourc3-Web-Client#3]
- [x] Send Empty
![image](https://user-images.githubusercontent.com/70755985/160803961-618c5e40-06cb-4a9b-a082-03bda88fc5d5.png)
- [x] Send
![image](https://user-images.githubusercontent.com/70755985/160804043-53d028af-c2c9-4ae7-839d-f857c34cb332.png)
- [x] Send Confirm
![image](https://user-images.githubusercontent.com/70755985/160804319-e98b084f-f85b-498f-8931-9fc994d8dbc1.png)

**Comment by kovaletskaterina** [comment]
Сhecked for compliance with the design
