### ISSUE TITLE
redisign receive Page

### ISSUE THREAD

**Issue by JenkJS** [SOURC3XYZ/Sourc3-Web-Client#4]
- [x] Recieve
![image](https://user-images.githubusercontent.com/70755985/161039612-b917c5d5-2740-4e26-a89c-f96787c5e273.png)
- [x] Recieve advanced
![image](https://user-images.githubusercontent.com/70755985/161039633-924de06d-83c7-47a5-a7dd-34344ea30e83.png)
- [x] Recieve qr
![image](https://user-images.githubusercontent.com/70755985/161039659-fe6859ea-2f83-4977-ae53-4f2a6a28c97a.png)

**Comment by kovaletskaterina** [comment]
checked for compliance with the design
