### ISSUE TITLE
redisign Popup

### ISSUE THREAD

**Issue by JenkJS** [SOURC3XYZ/Sourc3-Web-Client#5]
- [x] Restore
![image](https://user-images.githubusercontent.com/70755985/161040115-01994d53-df7f-433c-80a8-754c259c9f27.png)
![image](https://user-images.githubusercontent.com/70755985/161040169-bed5f379-18b7-44ed-aa69-de09973dcd3d.png)
- [x] Save phrase
![image](https://user-images.githubusercontent.com/70755985/161040186-eefd62af-293b-4a49-936d-7dbd0f1f5f7b.png)
- [x] quit
![image](https://user-images.githubusercontent.com/70755985/161040251-7743d323-4544-4ab7-bbfe-d9fdd406d466.png)
![image](https://user-images.githubusercontent.com/70755985/161040225-46e18d9d-3218-490e-8f17-245a0cff0f63.png)

**Comment by kovaletskaterina** [comment]
Сhecked for compliance with the design.
